# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.6.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.6.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/alexjohnson/Documents/CPSC385/Final Project"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/alexjohnson/Documents/CPSC385/Final Project"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.6.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/alexjohnson/Documents/CPSC385/Final Project/CMakeFiles" "/Users/alexjohnson/Documents/CPSC385/Final Project/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/alexjohnson/Documents/CPSC385/Final Project/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DecryptImage

# Build rule for target.
DecryptImage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DecryptImage
.PHONY : DecryptImage

# fast build rule for target.
DecryptImage/fast:
	$(MAKE) -f CMakeFiles/DecryptImage.dir/build.make CMakeFiles/DecryptImage.dir/build
.PHONY : DecryptImage/fast

#=============================================================================
# Target rules for targets named EncryptImage

# Build rule for target.
EncryptImage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EncryptImage
.PHONY : EncryptImage

# fast build rule for target.
EncryptImage/fast:
	$(MAKE) -f CMakeFiles/EncryptImage.dir/build.make CMakeFiles/EncryptImage.dir/build
.PHONY : EncryptImage/fast

DecryptImage.o: DecryptImage.cpp.o

.PHONY : DecryptImage.o

# target to build an object file
DecryptImage.cpp.o:
	$(MAKE) -f CMakeFiles/DecryptImage.dir/build.make CMakeFiles/DecryptImage.dir/DecryptImage.cpp.o
.PHONY : DecryptImage.cpp.o

DecryptImage.i: DecryptImage.cpp.i

.PHONY : DecryptImage.i

# target to preprocess a source file
DecryptImage.cpp.i:
	$(MAKE) -f CMakeFiles/DecryptImage.dir/build.make CMakeFiles/DecryptImage.dir/DecryptImage.cpp.i
.PHONY : DecryptImage.cpp.i

DecryptImage.s: DecryptImage.cpp.s

.PHONY : DecryptImage.s

# target to generate assembly for a file
DecryptImage.cpp.s:
	$(MAKE) -f CMakeFiles/DecryptImage.dir/build.make CMakeFiles/DecryptImage.dir/DecryptImage.cpp.s
.PHONY : DecryptImage.cpp.s

EncryptImage.o: EncryptImage.cpp.o

.PHONY : EncryptImage.o

# target to build an object file
EncryptImage.cpp.o:
	$(MAKE) -f CMakeFiles/EncryptImage.dir/build.make CMakeFiles/EncryptImage.dir/EncryptImage.cpp.o
.PHONY : EncryptImage.cpp.o

EncryptImage.i: EncryptImage.cpp.i

.PHONY : EncryptImage.i

# target to preprocess a source file
EncryptImage.cpp.i:
	$(MAKE) -f CMakeFiles/EncryptImage.dir/build.make CMakeFiles/EncryptImage.dir/EncryptImage.cpp.i
.PHONY : EncryptImage.cpp.i

EncryptImage.s: EncryptImage.cpp.s

.PHONY : EncryptImage.s

# target to generate assembly for a file
EncryptImage.cpp.s:
	$(MAKE) -f CMakeFiles/EncryptImage.dir/build.make CMakeFiles/EncryptImage.dir/EncryptImage.cpp.s
.PHONY : EncryptImage.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DecryptImage"
	@echo "... EncryptImage"
	@echo "... DecryptImage.o"
	@echo "... DecryptImage.i"
	@echo "... DecryptImage.s"
	@echo "... EncryptImage.o"
	@echo "... EncryptImage.i"
	@echo "... EncryptImage.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

