# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.6.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.6.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/alexjohnson/Documents/CPSC385/Final Project"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/alexjohnson/Documents/CPSC385/Final Project"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.6.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/alexjohnson/Documents/CPSC385/Final Project/CMakeFiles" "/Users/alexjohnson/Documents/CPSC385/Final Project/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/alexjohnson/Documents/CPSC385/Final Project/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EncryptImageDCT

# Build rule for target.
EncryptImageDCT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EncryptImageDCT
.PHONY : EncryptImageDCT

# fast build rule for target.
EncryptImageDCT/fast:
	$(MAKE) -f CMakeFiles/EncryptImageDCT.dir/build.make CMakeFiles/EncryptImageDCT.dir/build
.PHONY : EncryptImageDCT/fast

#=============================================================================
# Target rules for targets named DecryptImageLSB

# Build rule for target.
DecryptImageLSB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DecryptImageLSB
.PHONY : DecryptImageLSB

# fast build rule for target.
DecryptImageLSB/fast:
	$(MAKE) -f CMakeFiles/DecryptImageLSB.dir/build.make CMakeFiles/DecryptImageLSB.dir/build
.PHONY : DecryptImageLSB/fast

#=============================================================================
# Target rules for targets named EncryptImageLSB

# Build rule for target.
EncryptImageLSB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EncryptImageLSB
.PHONY : EncryptImageLSB

# fast build rule for target.
EncryptImageLSB/fast:
	$(MAKE) -f CMakeFiles/EncryptImageLSB.dir/build.make CMakeFiles/EncryptImageLSB.dir/build
.PHONY : EncryptImageLSB/fast

DecryptImageLSB.o: DecryptImageLSB.cpp.o

.PHONY : DecryptImageLSB.o

# target to build an object file
DecryptImageLSB.cpp.o:
	$(MAKE) -f CMakeFiles/DecryptImageLSB.dir/build.make CMakeFiles/DecryptImageLSB.dir/DecryptImageLSB.cpp.o
.PHONY : DecryptImageLSB.cpp.o

DecryptImageLSB.i: DecryptImageLSB.cpp.i

.PHONY : DecryptImageLSB.i

# target to preprocess a source file
DecryptImageLSB.cpp.i:
	$(MAKE) -f CMakeFiles/DecryptImageLSB.dir/build.make CMakeFiles/DecryptImageLSB.dir/DecryptImageLSB.cpp.i
.PHONY : DecryptImageLSB.cpp.i

DecryptImageLSB.s: DecryptImageLSB.cpp.s

.PHONY : DecryptImageLSB.s

# target to generate assembly for a file
DecryptImageLSB.cpp.s:
	$(MAKE) -f CMakeFiles/DecryptImageLSB.dir/build.make CMakeFiles/DecryptImageLSB.dir/DecryptImageLSB.cpp.s
.PHONY : DecryptImageLSB.cpp.s

EncryptImageDCT.o: EncryptImageDCT.cpp.o

.PHONY : EncryptImageDCT.o

# target to build an object file
EncryptImageDCT.cpp.o:
	$(MAKE) -f CMakeFiles/EncryptImageDCT.dir/build.make CMakeFiles/EncryptImageDCT.dir/EncryptImageDCT.cpp.o
.PHONY : EncryptImageDCT.cpp.o

EncryptImageDCT.i: EncryptImageDCT.cpp.i

.PHONY : EncryptImageDCT.i

# target to preprocess a source file
EncryptImageDCT.cpp.i:
	$(MAKE) -f CMakeFiles/EncryptImageDCT.dir/build.make CMakeFiles/EncryptImageDCT.dir/EncryptImageDCT.cpp.i
.PHONY : EncryptImageDCT.cpp.i

EncryptImageDCT.s: EncryptImageDCT.cpp.s

.PHONY : EncryptImageDCT.s

# target to generate assembly for a file
EncryptImageDCT.cpp.s:
	$(MAKE) -f CMakeFiles/EncryptImageDCT.dir/build.make CMakeFiles/EncryptImageDCT.dir/EncryptImageDCT.cpp.s
.PHONY : EncryptImageDCT.cpp.s

EncryptImageLSB.o: EncryptImageLSB.cpp.o

.PHONY : EncryptImageLSB.o

# target to build an object file
EncryptImageLSB.cpp.o:
	$(MAKE) -f CMakeFiles/EncryptImageLSB.dir/build.make CMakeFiles/EncryptImageLSB.dir/EncryptImageLSB.cpp.o
.PHONY : EncryptImageLSB.cpp.o

EncryptImageLSB.i: EncryptImageLSB.cpp.i

.PHONY : EncryptImageLSB.i

# target to preprocess a source file
EncryptImageLSB.cpp.i:
	$(MAKE) -f CMakeFiles/EncryptImageLSB.dir/build.make CMakeFiles/EncryptImageLSB.dir/EncryptImageLSB.cpp.i
.PHONY : EncryptImageLSB.cpp.i

EncryptImageLSB.s: EncryptImageLSB.cpp.s

.PHONY : EncryptImageLSB.s

# target to generate assembly for a file
EncryptImageLSB.cpp.s:
	$(MAKE) -f CMakeFiles/EncryptImageLSB.dir/build.make CMakeFiles/EncryptImageLSB.dir/EncryptImageLSB.cpp.s
.PHONY : EncryptImageLSB.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... EncryptImageDCT"
	@echo "... DecryptImageLSB"
	@echo "... EncryptImageLSB"
	@echo "... DecryptImageLSB.o"
	@echo "... DecryptImageLSB.i"
	@echo "... DecryptImageLSB.s"
	@echo "... EncryptImageDCT.o"
	@echo "... EncryptImageDCT.i"
	@echo "... EncryptImageDCT.s"
	@echo "... EncryptImageLSB.o"
	@echo "... EncryptImageLSB.i"
	@echo "... EncryptImageLSB.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

